import os
import re
from collections import Counter
from datetime import datetime
from openai import OpenAI

class LLM:
    def __init__(self):
        self.key = os.getenv("OPENAI_API_KEY", "").strip()
        self.model = os.getenv("OPENAI_MODEL", "gpt-5")
        self.client = OpenAI(api_key=self.key) if self.key else None

    @property
    def available(self):
        return self.client is not None

    def __call__(self, prompt, web=False):
        if not self.client:
            return self.demo(prompt)
        tools = [{"type": "web_search"}] if web else None
        kwargs = {"model": self.model, "input": prompt}
        if tools:
            kwargs["tools"] = tools
        response = self.client.responses.create(**kwargs)
        return response.output_text

    def demo(self, prompt):
        p = prompt.lower()
        if "research" in p or "references" in p:
            return """Research summary (DEMO MODE):
The observed pattern is consistent with repeated authentication failures,
which is commonly associated with brute-force or password-guessing activity.
Defensive controls include MFA, rate limiting, strong passwords, monitoring,
and automated blocking where appropriate.

References:
- MITRE ATT&CK: Credential Access / Brute Force
- OWASP: Authentication guidance
"""
        if "report" in p:
            return "See the structured report generated by the Report Agent. DEMO MODE was used because no API key was configured."
        return """Based on the supplied evidence, repeated failed authentication
attempts from the same source indicate suspicious login activity. A high
severity rating is appropriate when attempts are frequent or followed by
successful authentication. Recommended controls include MFA, rate limiting,
blocking or monitoring the source, and reviewing successful sessions."""

class SecurityAnalystAgent:
    def analyze(self, text):
        lines = [x.strip() for x in text.splitlines() if x.strip()]
        failed = [x for x in lines if "failed password" in x.lower() or "failed login" in x.lower()]
        accepted = [x for x in lines if "accepted password" in x.lower() or "successful login" in x.lower()]
        ips = []
        for line in failed:
            m = re.search(r"\b(?:\d{1,3}\.){3}\d{1,3}\b", line)
            if m:
                ips.append(m.group())
        counts = Counter(ips)
        repeated = counts.most_common()
        severity = "LOW"
        if len(failed) >= 5:
            severity = "HIGH"
        elif len(failed) >= 3:
            severity = "MEDIUM"
        if accepted and failed:
            severity = "CRITICAL" if len(failed) >= 5 else "HIGH"

        threats = []
        if len(failed) >= 3:
            threats.append("Possible SSH/authentication brute-force activity")
        if accepted and failed:
            threats.append("Successful authentication occurred in the broader event set; investigate for possible account compromise")

        mitigations = [
            "Enable multi-factor authentication where supported",
            "Use strong unique passwords or SSH keys",
            "Apply rate limiting/account lockout carefully",
            "Review and monitor successful logins after repeated failures",
            "Block or investigate suspicious sources according to organizational policy",
            "Preserve logs and timestamps for incident investigation",
        ]
        return {
            "severity": severity,
            "failed_attempts": len(failed),
            "successful_logins": len(accepted),
            "source_ips": repeated,
            "threats": threats or ["No strong automated threat indicator detected"],
            "mitigations": mitigations,
            "evidence": lines[:30],
        }

class ResearchAgent:
    def run(self, objective, analyst, llm):
        prompt = f"""Act as a cybersecurity research analyst.
Research objective: {objective}
Observed analysis:
{analyst}
Provide a concise defensive research summary, explain the likely technique,
and provide trustworthy references. Do not invent citations."""
        return llm(prompt, web=True)

class ReportAgent:
    def run(self, question, analyst, research, rag_answer=""):
        bullets = "\n".join("- " + x for x in analyst["threats"])
        mits = "\n".join("- " + x for x in analyst["mitigations"])
        refs = research.strip() if research else "No external research was requested."
        return f"""# Cybersecurity Multi-Agent Investigation Report

## Investigation Objective
{question}

## Severity
**{analyst['severity']}**

## Observed Evidence
- Failed authentication attempts: {analyst['failed_attempts']}
- Successful logins: {analyst['successful_logins']}
- Source IPs: {analyst['source_ips']}

## Potential Threats
{bullets}

## Recommended Mitigation
{mits}

## Document/RAG Finding
{rag_answer or "No document was supplied."}

## Research Findings and References
{refs}

## Analyst Note
This report separates observed log evidence from inferred threat classification.
Further investigation should validate account ownership, source reputation,
successful sessions, and host context.
"""

class Orchestrator:
    def __init__(self, llm, rag):
        self.llm = llm
        self.rag = rag
        self.analyst = SecurityAnalystAgent()
        self.research = ResearchAgent()
        self.report = ReportAgent()

    def run(self, question, log_text, use_research=True):
        analyst = self.analyst.analyze(log_text)
        rag_answer = ""
        if self.rag.chunks:
            rag_answer, _ = self.rag.answer(question, self.llm)
        research = self.research.run(question, analyst, self.llm) if use_research else ""
        final = self.report.run(question, analyst, research, rag_answer)
        return {
            "analyst": analyst,
            "research": research,
            "rag_answer": rag_answer,
            "report": final,
        }
