"""
Synthetic expense reports for the compliance agent to evaluate. Deliberately
mixed: some violate mechanically-checkable rules, some are clean, and a few
are Meals expenses that only differ by description (client-facing vs not)
to exercise the LLM's context review.
"""

SYNTHETIC_EXPENSES = [
    {
        "employee": "Alex Torres",
        "date": "2024-03-01",
        "submitted_date": "2024-03-04",
        "category": "Personal Software",
        "amount": 9.99,
        "description": "Personal Spotify Premium subscription.",
        "receipt_attached": True,
        "pre_approved": False,
    },
    {
        "employee": "Bailey Nguyen",
        "date": "2024-03-05",
        "submitted_date": "2024-03-08",
        "category": "Meals",
        "amount": 180.00,
        "description": "Dinner with existing client to discuss contract renewal terms.",
        "receipt_attached": True,
        "pre_approved": True,
    },
    {
        "employee": "Casey Brooks",
        "date": "2024-03-06",
        "submitted_date": "2024-03-07",
        "category": "Commuting",
        "amount": 22.00,
        "description": "Uber ride from home to the office.",
        "receipt_attached": True,
        "pre_approved": False,
    },
    {
        "employee": "Dee Park",
        "date": "2024-03-07",
        "submitted_date": "2024-03-09",
        "category": "Alcohol",
        "amount": 85.00,
        "description": "Bottle of wine for a client appreciation dinner.",
        "receipt_attached": True,
        "pre_approved": True,
    },
    {
        "employee": "Evan Marsh",
        "date": "2024-03-08",
        "submitted_date": "2024-03-10",
        "category": "Office Supplies",
        "amount": 45.00,
        "description": "Notebooks and pens for the team.",
        "receipt_attached": False,
        "pre_approved": False,
    },
    {
        "employee": "Farah Haddad",
        "date": "2024-03-01",
        "submitted_date": "2024-03-03",
        "category": "Travel",
        "amount": 620.00,
        "description": "Round-trip flight for the regional sales conference.",
        "receipt_attached": True,
        "pre_approved": False,
    },
    {
        "employee": "Grant Oduya",
        "date": "2024-03-09",
        "submitted_date": "2024-03-10",
        "category": "Meals",
        "amount": 18.00,
        "description": "Lunch at my desk while working through the break, no client involved.",
        "receipt_attached": True,
        "pre_approved": False,
    },
    {
        "employee": "Harper Lin",
        "date": "2024-02-20",
        "submitted_date": "2024-03-01",
        "category": "Training",
        "amount": 450.00,
        "description": "Registration fee for an industry conference.",
        "receipt_attached": True,
        "pre_approved": True,
    },
    {
        "employee": "Iris Weber",
        "date": "2024-03-02",
        "submitted_date": "2024-03-05",
        "category": "Meals",
        "amount": 95.00,
        "description": "Team celebration lunch for hitting our quarterly goal, no clients present.",
        "receipt_attached": True,
        "pre_approved": True,
    },
    {
        "employee": "Jamal Foster",
        "date": "2024-01-05",
        "submitted_date": "2024-03-01",
        "category": "Office Supplies",
        "amount": 30.00,
        "description": "Replacement keyboard and mouse.",
        "receipt_attached": True,
        "pre_approved": False,
    },
]
